WaterCompany/Areas/Admin/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaterCompany.Core;
using WaterCompanyViewModel.Admin;

namespace WaterCompany.Areas.Admin.Controllers
{
    public class RegionController : Controller
    {
        // GET: Admin/Region
        #region Actions
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Search()
        {
            var model = "RegionSelect".ExecuParamsSqlOrStored(false).AsList<RegionVM>();

            return PartialView(model);
        }
        [HttpGet]
        public ActionResult Create(int CarId = 0, int MangerId = 0)
        {
           

            RegionVM obj = new RegionVM();
            return PartialView("~/Areas/Admin/Views/Region/Create.cshtml", obj);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
          
            var model = "RegionSelectById".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsList<RegionVM>();
            return PartialView("~/Areas/Admin/Views/Region/Create.cshtml", model.FirstOrDefault());
        }
        [HttpPost]

        public ActionResult Create(RegionVM model)
        {


            var data = "RegionInsert".ExecuParamsSqlOrStored(false, "Name".KVP(model.Name),
               
               
                "Id".KVP(model.Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "Add Success", JsonRequestBehavior.AllowGet);


            }


            return Json("error," + " Error", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int Id)
        {
            //var data = "DriversDelete".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            RegionVM obj = new RegionVM();
            obj.Id = Id;
            return PartialView("~/Areas/Admin/Views/Region/Delete.cshtml", obj);



        }
        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "RegionDelete".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();

            if (data == 1)
                return Json("success," + "Delete Success", JsonRequestBehavior.AllowGet);
            else
                return Json("error," + "Error", JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

WaterCompany/Areas/Admin/Views/Region/Create.cshtml
@model WaterCompanyViewModel.Admin.RegionVM



@using (Html.BeginForm("Create", "Region", new { area = "Admin" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @*@<div id="myModalAdd" class="modal fade" role="dialog">*@
    <div class="modal-dialog">
        <div class="modal-content" style="width: 900px;">
            <div class="modal-header">
                @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
                <h4 class="modal-title">تفاصيل المنتجات</h4>
            </div>
            <div class="modal-body" style="width :900px;">
                <div class="panel">
                    @*<div class="panel-heading">
                        <span class="panel-title hidden-xs">@ProductRes.Details</span>
                    </div>*@
                    <div class="panel-body p25 pb5">
                        <div class="tab-content pn br-n admin-form">
                            <div id="tab1_1" class="tab-pane active">
                                @Html.HiddenFor(model => model.Id)

                                <div class="row">
                                    <div class="col-md-2">
                                        <label>  اسم المنطقه    </label>
                                    </div>
                                    <div class="col-md-4">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control input-circle" } })
                                    </div>
                                   
                                </div>
                               
                                <br />
                                <div class="row">
                                    <div class="col-md-1">

                                    </div>
                                    <div class="col-md-3">
                                        <input type="button" value="حفظ" class="btn yellow Saveee" onclick="Save()" />
                                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                        </div>
                    </div>
                    </div>

                    }



<script>
    $(document).ready(function () {
        $("input[type=text]").addClass("gui-input");
    });
</script>

WaterCompany/Areas/Admin/Views/Region/Delete.cshtml
@model WaterCompanyViewModel.Admin.RegionVM


    <div class="modal-dialog" style="width: 900px;">
        <div class="modal-content">
            <div class="modal-header">
                @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
                <h4 class="modal-title"> حذف </h4>
            </div>
            <div class="modal-body" style="width :900px;">
          
                <h4 class="modal-title"> هل تريد الحذف</h4>
                <div class="row">
                    <div class="col-md-3">
                        <input type="button" value="حذف" class="btn yellow Saveee" onclick="DeleteRow(@Model.Id)" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

WaterCompany/Areas/Admin/Views/Region/Index.cshtml
@model  WaterCompanyViewModel.Admin.RegionVM

    @{
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
    <br /><br /><br />
    <div class="portlet box grey-cascade">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-globe"></i>
                <span style="font-weight:bold;">بحث</span>
            </div>
            <div class="tools">
                <a href="javascript:;" class="expand" data-original-title="" title=""></a>
            </div>
        </div>
        <div class="portlet-body">
            <div id="SearchCriteria">
                @using (Html.BeginForm("Search", "Region", new { area = "Admin" }, FormMethod.Get, new { id = "SearchForm" }))
                {
                    @*<div class="row">
                            <div class="col-md-1">
                                @Html.LabelFor(model => model.NameSm, htmlAttributes: new { @class = "control-label" })
                            </div>
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.NameSm, new { htmlAttributes = new { @class = "form-control input-circle" } })
                            </div>
                        </div>*@
                    <br />
                    <div class="row">
                        <div class="text-center">
                            @*<input type="button" value="بحث" id="btnSearch" class="btn btn-circle yellow" onclick="Search()"/>*@
                            @*<input type="button" value="@GlobalRes.btnShowAll" id="ShowAll" class="btn btn-circle yellow" onclick="SearchAll()"/>*@
                            <input type="button" id="AddNew" onclick="Create()" class="btn btn-circle blue New" value="اضافه جديد" />
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="icon-settings font-dark"></i>
                        @*<span class="caption-subject bold uppercase">@GlobalRes.SearchResult</span>*@
                    </div>
                    <div class="tools"></div>
                    <div id="SearchResultTitle" class="pull-right">
                        @*@Html.Editor("PageSize", "PageSizeSelector")*@
                    </div>
                </div>
                <div class="portlet-body">
                    <div id="SearchResult">
                        <div id="SearchTableContainer"></div>
                    </div>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
    <div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

    @section scripts
{
        @*<script src="@Url.Content("~/Areas/Product/Scripts/manageProduct.js")"></script>*@
        @*<script src="~/Areas/Admin/Scripts/Product.js"></script>*@
        <script src="~/Areas/Admin/Scripts/Region.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                manageRegion.init();
            });
        </script>
    }

WaterCompany/Areas/Admin/Views/Region/Search.cshtml
@model IEnumerable <WaterCompanyViewModel.Admin.RegionVM>

@{ 
    Layout = null;
}
<div class="panel">
    <table id="dt_basic" class="table table-striped table-bordered table-hover datatable" width="100%">
        <thead>
            <tr>
                <th>التسلسل</th>
                <th>الاسم </th>
               

                <th>الاعدادات</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                


                <td>
                    <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                        <button class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-cog fa-lg"></i>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-xs pull-right">
                            <li>
                                <input type="button" id="btnUpdate" onclick="Edit(@item.Id)" value="تعديل" />
                            </li>
                            <li class="divider"></li>
                            <li>
                                <input type="button" id="btnDelete" onclick="Delete(@item.Id)" value="حذف" />
                            </li>
                            <li class="divider"></li>
                            <li class="text-align-center">
                                <a href="javascript:void(0);">الغاء</a>
                            </li>
                        </ul>
                    </div>
                </td>

            </tr>
        }
        </tbody>
    </table>
</div>
<script type="text/javascript">
        $(function () {
            $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            } );


</script>