WaterCompany/Areas/Admin/Controllers/AgreementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaterCompany.Core;
using WaterCompanyViewModel.Admin;

namespace WaterCompany.Areas.Admin.Controllers
{
    public class AgreementController : Controller
    {
        public List<AgreementProductVM> _ListProduct;

        // GET: Admin/Agreement
        #region Actions
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult Search()
        {
            var model = "AgreementsSelectAll".ExecuParamsSqlOrStored(false).AsList<AgreementVM>();

            return PartialView(model);

        }

        [HttpGet]
        public ActionResult Create(int CarId = 0, int DelegateId=0,int DriverId=0,int ProductId=0)
        {
            // AgreementVM obj = new AgreementVM();

            var lst3 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst3.AddRange("CarDrop".ExecuParamsSqlOrStored(false).AsList<CarDrop>().Select(s => new SelectListItem
            {
                Text = s.TypeCars + s.NumberCars,
                Value = s.Id.ToString(),
                Selected = s.Id == CarId ? true : false
            }).ToList());
            ViewBag.CarId = lst3;

            var lst2 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst2.AddRange("DelegateDrop".ExecuParamsSqlOrStored(false).AsList<EmployeeDrop>().Select(s => new SelectListItem
            {
                Text = s.NameAr,
                Value = s.Id.ToString(),
                Selected = s.Id == DelegateId ? true : false
            }).ToList());
            ViewBag.DelegatId = lst2;
            var lst4 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst4.AddRange("DriverDrop".ExecuParamsSqlOrStored(false).AsList<EmployeeDrop>().Select(s => new SelectListItem
            {
                Text = s.NameAr,
                Value = s.Id.ToString(),
                Selected = s.Id == DriverId ? true : false
            }).ToList());
            ViewBag.DriverId = lst4;
            var lst5 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst5.AddRange("ProductDrop".ExecuParamsSqlOrStored(false).AsList<EmployeeDrop>().Select(s => new SelectListItem
            {
                Text = s.NameAr,
                Value = s.Id.ToString(),
                Selected = s.Id == ProductId ? true : false
            }).ToList());
            ViewBag.ProductId = lst5;
            var lst6 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst6.AddRange("Sp_RegionDrop".ExecuParamsSqlOrStored(false).AsList<RegionVM>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());
            ViewBag.RegionId = lst6;

            TempData["AgreementProduct"] = null;
            //return PartialView("~/Areas/Agreement/Views/ManageAgreement/Create.cshtml");
            return View();
        }

        public decimal getProductPrice(string productId)
        {
            //var res = _commonService.FindProductPrice(int.Parse(productId));
            var model = "ProductPriceSelect".ExecuParamsSqlOrStored(false, "productId".KVP(productId)).AsList<PriceSelect>().FirstOrDefault();
            return (model.Price);

        }

        [HttpPost]

        public JsonResult AddAgreementProduct(string ProductName, int ProductId, decimal Price, string Target)
        {
            TempData.Keep();

            AgreementProductVM obj = new AgreementProductVM();
            obj.Id = ProductId;
            obj.Price = Price;
            obj.Target = Target;
            obj.Name = ProductName;

            if (TempData["AgreementProduct"] != null)
            {

                _ListProduct = TempData["AgreementProduct"] as List<AgreementProductVM>;
                _ListProduct.Add(obj);
                TempData["AgreementProduct"] = _ListProduct;

            }
            else
            {
                _ListProduct = new List<AgreementProductVM>();
                _ListProduct.Add(obj);
                TempData["AgreementProduct"] = _ListProduct;
            }


            return Json("success," + "Add Success", JsonRequestBehavior.AllowGet);
        }

        public ActionResult SearchProduct(string RequestId)
        {
            TempData.Keep();

            var data = "AgreementsProductsSelectAll".ExecuParamsSqlOrStored(false, "RequestId".KVP(RequestId)).AsList<AgreementProductVM>();

            //var data = _AgreementService.FindAllProducts(int.Parse(RequestId == "" ? "0" : RequestId));
            if (data.Count() > 0)
            {
                for (int i = 0; i < data.Count(); i++)
                {
                    AgreementProductVM obj = new AgreementProductVM();
                    obj.Id = data[i].Id;
                    obj.Price = data[i].Price;
                    obj.Target = data[i].Target;
                    obj.Name = data[i].Name;

                    if (TempData["AgreementProduct"] != null)
                    {

                        _ListProduct = TempData["AgreementProduct"] as List<AgreementProductVM>;
                        _ListProduct.Add(obj);
                        TempData["AgreementProduct"] = _ListProduct;

                    }
                    else
                    {
                        _ListProduct = new List<AgreementProductVM>();
                        _ListProduct.Add(obj);
                        TempData["AgreementProduct"] = _ListProduct;
                    }

                }
                return PartialView("~/Areas/Agreement/Views/Agreement/SearchProduct.cshtml", _ListProduct);
            }
            else
            {
                if (TempData["AgreementProduct"] != null)
                {
                    _ListProduct = TempData["AgreementProduct"] as List<AgreementProductVM>;
                }
                else
                {
                    _ListProduct = new List<AgreementProductVM>();
                }

                return PartialView("~/Areas/Admin/Views/Agreement/SearchProduct.cshtml", _ListProduct);
            }

        }
        [HttpPost]
        public JsonResult Create(AgreementFM viewModel)
        {

            var result = "AgreementsInsert".ExecuParamsSqlOrStored(false, "StartDate".KVP(viewModel.StartDate),
               "EndDate".KVP(viewModel.EndDate), "Area".KVP(viewModel.Area), "DelegatId".KVP(viewModel.DelegatId),
               "CarId".KVP(viewModel.CarId), "DriverId".KVP(viewModel.DriverId), "Note".KVP(viewModel.Note),
               "RegionId".KVP(viewModel.RegionId),

               "Id".KVP(viewModel.Id)).AsNonQuery();

            //string result = _AgreementService.Save(viewModel);

            if (result != 0)
            {
                var model = "AgreementsSelectAll".ExecuParamsSqlOrStored(false).AsList<AgreementVM>().LastOrDefault();
                var resultDeleteAll = "AgreementsProductsDeleteAll".ExecuParamsSqlOrStored(false, "RequestId".KVP(model.Id)).AsNonQuery();
                //string resultDeleteAll = _AgreementService.DeleteProductAll(int.Parse(result));
                _ListProduct = TempData["AgreementProduct"] as List<AgreementProductVM>;
                if (_ListProduct != null)
                {

                    for (int i = 0; i < _ListProduct.Count(); i++)
                    {
                        result = "AgreementsProductsInsert".ExecuParamsSqlOrStored(false, "RequestId".KVP(model.Id),
             "ProductId".KVP(_ListProduct[i].Id), "Price".KVP(_ListProduct[i].Price), "TargetSelling".KVP(_ListProduct[i].Target)
             ).AsNonQuery();

                        //result = _AgreementService.SaveProduct(int.Parse(result), _ListProduct[i].Id, _ListProduct[i].Price, _ListProduct[i].Target, viewModel.CreatedBy);
                    }
                }
                return Json("success," + "Add Success", JsonRequestBehavior.AllowGet);
            }
            else
                return Json("error," + " Error", JsonRequestBehavior.AllowGet);

        }
        //[HttpPost]
        //public JsonResult Create(AgreementVM viewModel)
        //{

        //    viewModel.CreatedBy = 1;

        //    string result = _AgreementService.Save(viewModel);
        //    if (result != "0")
        //    {
        //        string resultDeleteAll = _AgreementService.DeleteProductAll(int.Parse(result));
        //        _ListProduct = TempData["AgreementProduct"] as List<ProductVm>;
        //        if (_ListProduct != null)
        //        {

        //            for (int i = 0; i < _ListProduct.Count(); i++)
        //            {
        //                result = _AgreementService.SaveProduct(int.Parse(result), _ListProduct[i].Id, _ListProduct[i].Price, _ListProduct[i].Target, viewModel.CreatedBy);
        //            }
        //        }
        //        return Json("success," + "Add Success", JsonRequestBehavior.AllowGet);
        //    }
        //    else
        //        return Json("error," + " Error", JsonRequestBehavior.AllowGet);

        //}

        //[HttpGet]
        //public ActionResult Edit(string id)
        //{

        //    AgreementVM _viewModel = _AgreementService.GetById(int.Parse(id));

        //    ViewBag.CarId = _commonService.FindCars(_viewModel.CarId);
        //    ViewBag.DelegatId = _commonService.FindDelegates(_viewModel.DelegatId);
        //    ViewBag.DriverId = _commonService.FindDrivers(_viewModel.DriverId);
        //    ViewBag.ProductId = _commonService.FindProducts();

        //    // return PartialView("~/Areas/Agreement/Views/ManageAgreement/Create.cshtml", _viewModel);

WaterCompany/Areas/Admin/Views/Agreement/Create.cshtml
@model  WaterCompanyViewModel.Admin.AgreementFM
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br /><br /><br />
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>
            <span style="font-weight:bold;">التفاصيل</span>
        </div>
        <div class="tools">
            <a href="javascript:;" class="expand" data-original-title="" title=""></a>
        </div>
    </div>
    <div class="portlet-body">
        <div id="SearchCriteria">
            @using (Html.BeginForm("Create", "Agreement", new { area = "Agreement" }, System.Web.Mvc.FormMethod.Post, new { id = "ModelForm", enctype = "multipart/form-data" }))
            {
                <div class="row">
                    <div class="col-md-1">
                        @Html.HiddenFor(model => model.Id)
                        @Html.HiddenFor(model => model.RequestId)
                        <label> تاريخ البدايه  </label>
                    </div>
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control input-circle datepicker" } })
                    </div>
                    <div class="col-md-1">
                        <label> تاريخ النهايه  </label>
                    </div>
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control  input-circle datepicker" } })
                    </div>
                    <div class="col-md-1">
                        <label> المنطقه   </label>
                    </div>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => Model.RegionId, (List<SelectListItem>)ViewBag.RegionList, new { @class = "form-control input-circle" })
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-1">
                        <label> المندوب   </label>
                    </div>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => Model.DelegatId, (List<SelectListItem>)ViewBag.DelegatId, new { @class = "form-control" })
                    </div>
                    <div class="col-md-1">
                        <label> السيارة   </label>
                    </div>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => Model.CarId, (List<SelectListItem>)ViewBag.CarId, new { @class = "form-control" })
                    </div>
                    <div class="col-md-1">
                        <label> السائق   </label>
                    </div>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => Model.DriverId, (List<SelectListItem>)ViewBag.DriverId, new { @class = "form-control" })
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-1">
                        <label> تفاصيل   </label>
                    </div>
                    <div class="col-md-11">
                        @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control input-circle" } })
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-1">
                        <label> المنتج   </label>
                    </div>
                    <div class="col-md-3">
                        @Html.DropDownListFor(x => Model.ProductId, (List<SelectListItem>)ViewBag.ProductId, new { @class = "form-control" })
                    </div>
                    <div class="col-md-1">
                        <label> السعر   </label>
                    </div>
                    <div class="col-md-2">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control input-circle", @readonly = "readonly" } })
                    </div>
                    <div class="col-md-1">
                        <label> الهدف المبيعى   </label>
                    </div>
                    <div class="col-md-3">
                        @Html.EditorFor(model => model.Target, new { htmlAttributes = new { @class = "form-control input-circle" } })
                    </div>
                    <div class="col-md-1">
                        <input type="button" value="حفظ" class="btn yellow Saveee" onclick="AddProduct()" />
                    </div>
                    @*<div class="col-md-3">
                            @Html.EditorFor(model => model.Target, new { htmlAttributes = new { @class = "form-control input-circle" } })
                        </div>*@
                </div>
                @*<br />*@
                <div class="row">
                    <div class="col-md-12">
                        <!-- BEGIN EXAMPLE TABLE PORTLET-->
                        <div class="portlet light bordered">
                            @*<div class="portlet-title">
                                    <div class="caption font-dark">
                                        <i class="icon-settings font-dark"></i>
                                        <span class="caption-subject bold uppercase">@GlobalRes.Product</span>
                                    </div>
                                </div>*@
                            <div class="caption">
                                <i class="fa fa-globe"></i>
                                <span style="font-weight:bold;">المنتجات</span>
                            </div>
                            <div class="portlet-body">
                                <div id="SearchResult">
                                    <div id="SearchTableContainerProduct"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END EXAMPLE TABLE PORTLET-->
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="col-md-1">

                    </div>
                    <div class="col-md-3">
                        <input type="button" value="حفظ" class="btn yellow Saveee" onclick="Save()" />
                        <button type="button" class="btn btn-default" data-dismiss="modal">الغاء</button>
                    </div>
                </div>
            }
        </div>
    </div>
</div>


@*<div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>*@

@section scripts
{
    @*<script src="@Url.Content("~/Areas/Agreement/Scripts/manageAgreement.js")"></script>*@
    @*<script src="~/Areas/Admin/Scripts/Agreement.js"></script>*@
    <script src="~/Areas/Admin/Scripts/Agreement.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            //manageAgreement.init();

            SearchProduct($("#RequestId").val());

            $("input[type=text]").addClass("gui-input");

            $("#StartDate").datepicker("setDate", 'yyyy-mm-dd');
            $("#EndDate").datepicker("setDate", 'yyyy-mm-dd');

            // LoadChangeCurruncy();
            $('.datepicker').datepicker({
                dateFormat: 'yy-mm-dd'
            });

            $("#ProductId").change(function () {

                var selectedType = $('#ProductId').val();
                $.ajax({
                    type: "POST",
                    data: { "productId": selectedType },
                    url: "../Agreement/getProductPrice",
                    dataType: 'json',
                    success: function (data) {
                        $('#Price').val(data);
                    }
                });
            });
        });
    </script>
}

WaterCompany/Areas/Admin/Views/Agreement/Index.cshtml
@model  WaterCompanyViewModel.Admin.AgreementVM

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br /><br /><br />
<div class="portlet box grey-cascade">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-globe"></i>
            <span style="font-weight:bold;">بحث</span>
        </div>
        <div class="tools">
            <a href="javascript:;" class="expand" data-original-title="" title=""></a>
        </div>
    </div>
    <div class="portlet-body">
        <div id="SearchCriteria">
            @using (Html.BeginForm("Search", "Agreement", new { area = "Admin" }, FormMethod.Get, new { id = "SearchForm" }))
            {
                @*<div class="row">
                        <div class="col-md-1">
                            @Html.LabelFor(model => model.NameSm, htmlAttributes: new { @class = "control-label" })
                        </div>
                        <div class="col-md-3">
                            @Html.EditorFor(model => model.NameSm, new { htmlAttributes = new { @class = "form-control input-circle" } })
                        </div>
                    </div>*@
                <br />
                <div class="row">
                    <div class="text-center">
                        @*<input type="button" value="بحث" id="btnSearch" class="btn btn-circle yellow" onclick="Search()"/>*@
                        @*<input type="button" value="@GlobalRes.btnShowAll" id="ShowAll" class="btn btn-circle yellow" onclick="SearchAll()"/>*@
                        <a  id="AddNew"  class="btn btn-circle blue New" href="@Url.Action("Create")"  >اضافه جديد</a>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet light bordered">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="icon-settings font-dark"></i>
                    @*<span class="caption-subject bold uppercase">@GlobalRes.SearchResult</span>*@
                </div>
                <div class="tools"></div>
                <div id="SearchResultTitle" class="pull-right">
                    @*@Html.Editor("PageSize", "PageSizeSelector")*@
                </div>
            </div>
            <div class="portlet-body">
                <div id="SearchResult">
                    <div id="SearchTableContainer"></div>
                </div>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
<div class="modal fade" id="myModalAddEdit" role="dialog" data-backdrop="static"></div>

@section scripts
{
    @*<script src="@Url.Content("~/Areas/Product/Scripts/manageProduct.js")"></script>*@
    @*<script src="~/Areas/Admin/Scripts/Product.js"></script>*@
    @*<script src="~/Areas/Admin/Scripts/Employee.js"></script>*@
    <script src="~/Areas/Admin/Scripts/Agreement.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            Agreement.init();
        });
    </script>
}

WaterCompany/Areas/Admin/Views/Agreement/Search.cshtml
@model IEnumerable <WaterCompanyViewModel.Admin.AgreementVM>

@{ 
    Layout = null;
}
<div class="panel">
    <table id="dt_basic" class="table table-striped table-bordered table-hover datatable" width="100%">
        <thead>
            <tr>
                <th>التسلسل</th>
                <th>تاريخ البدايه </th>
                <th>تاريخ النهايه</th>
                <th> المنطقه</th>
                <th> المندوب</th>
                <th> السياره</th>





                <th>الاعدادات</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.StartDate</td>

                <td>@item.EndDate</td>
                <td>@item.RegionName</td>
                <td>@item.Delegat</td>
                <td>@item.Car</td>



                <td>
                    <div class="btn-group display-inline pull-right text-align-left hidden-tablet">
                        <button class="btn btn-xs btn-default dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-cog fa-lg"></i>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-xs pull-right">
                            <li>
                                <input type="button" id="btnUpdate" onclick="Edit(@item.Id)" value="تعديل" />
                            </li>
                            <li class="divider"></li>
                            <li>
                                <input type="button" id="btnDelete" onclick="Delete(@item.Id)" value="حذف" />
                            </li>
                            <li class="divider"></li>
                            <li class="text-align-center">
                                <a href="javascript:void(0);">الغاء</a>
                            </li>
                        </ul>
                    </div>
                </td>

            </tr>
        }
        </tbody>
    </table>
</div>
<script type="text/javascript">
        $(function () {
            $('.datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            } );


</script>

WaterCompany/Areas/Admin/Views/Agreement/SearchProduct.cshtml
@model IEnumerable<WaterCompanyViewModel.Admin.AgreementProductVM>

<div class="panel">
    <table  class="table table-striped table-bordered table-hover datatable" width="100%">
        <thead>
            <tr>
                <th>التسلسل</th>
                <th>اسم المنتج</th>
                <th>السعر</th>
                <th>الهدف المبيعى</th>
                @*<th>نسبه المنتدوب</th>
                <th>نسبه السائق</th>*@
                <th></th>
            </tr>
        </thead>
        <tbody>
         @foreach (var item in Model)
        {
                <tr id="@item.Id">
                    <td >@item.Id</td>
                    <td >@item.Name</td>
                    <td>@item.Price</td>
                    <td>@item.Target</td>
                     @*<td>@item.DelegetPercent</td>
                    <td>@item.DriverPercent</td>*@
                    <td><input type="button" id="btnDelete" onclick="DeleteProduct(@item.Id)" value="حذف" /></td>

                </tr>
        }
        </tbody>
    </table>
</div>

<script type="text/javascript">
        //$(function () {
        //    $('.datatable').DataTable();

        //        //Buttons examples
        //        var table = $('#datatable-buttons').DataTable({
        //            lengthChange: false,
        //            buttons: ['copy', 'excel', 'pdf']
        //        });

        //        table.buttons().container()
        //                .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
        //    } );

</script>
