WaterCompany/Areas/Admin/Controllers/DelegateController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WaterCompany.Core;
using WaterCompany.Models;
using WaterCompanyViewModel.Admin;

namespace WaterCompany.Areas.Admin.Controllers
{
    public class DelegateController : Controller
    {
        // GET: Admin/Delegate
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;


        public ActionResult Index()
        {
            //var model = "ProductsSelectAll".ExecuParamsSqlOrStored(false).AsList<DelegateVM>();
            return View();
        }
        public ActionResult Search()
        {
            var model = "DelegatesSelect".ExecuParamsSqlOrStored(false).AsList<DelegateVM>();

            return PartialView(model);
        }
        [HttpGet]
        public ActionResult Create()
        {

            var lst = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst.AddRange("Sp_RegionDrop".ExecuParamsSqlOrStored(false).AsList<RegionVM>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());
            ViewBag.RegionList = lst;
            DelagateFM obj = new DelagateFM();
            return PartialView("~/Areas/Admin/Views/Delegate/Create.cshtml", obj);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var lst = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst.AddRange("Sp_RegionDrop".ExecuParamsSqlOrStored(false).AsList<RegionVM>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());
            ViewBag.RegionList = lst;
            var model = "DelegatesSelectById".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsList<DelagateFM>();
            return PartialView("~/Areas/Admin/Views/Delegate/Create.cshtml", model.FirstOrDefault());
        }
        [HttpPost]

        public async Task<ActionResult> Create(DelagateFM model)
        {




            var data = "DelegatesInsert".ExecuParamsSqlOrStored(false, "NameAr".KVP(model.NameAr),
                "NameEn".KVP(model.NameEn), "PercentAmount".KVP(model.PercentAmount),
                "Telephone".KVP(model.Telephone), "Address".KVP(model.Address),
                "Area".KVP(model.Area), "Note".KVP(model.Note),
                "RegionId".KVP(model.RegionId),
                "Id".KVP(model.Id)).AsNonQuery();

            if (data != 0)
            {
                if (model.Id == 0)
                {
                    var modeluser = "DelegatesSelect".ExecuParamsSqlOrStored(false).AsList<DelegateVM>();
                    int userid = modeluser.LastOrDefault().Id;
                    var user = new ApplicationUser { UserName = model.UserName, Email = "asa"+userid+"s@yahoo.com", UserType = true, UserId = userid };
                    var result = await UserManager.CreateAsync(user, model.Password);
                    if (result.Succeeded)
                    {

                        // For more information on how to enable account confirmation and password reset please visit https://go.microsoft.com/fwlink/?LinkID=320771
                        // Send an email with this link
                        // string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                        // var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                        // await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                        return Json("success," + "Add Success", JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json("success," + "Update Success", JsonRequestBehavior.AllowGet);


                }

            }

            return Json("error," + " Error", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int Id)
        {
            //var data = "SP_DeleteCategory".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            DelegateVM obj = new DelegateVM();
            obj.Id = Id;
            return PartialView("~/Areas/Admin/Views/Delegate/Delete.cshtml", obj);



        }
        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "DelegatesDelete".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();

            if (data == 1)
                return Json("success," + "Delete Success", JsonRequestBehavior.AllowGet);
            else
                return Json("error," + "Error", JsonRequestBehavior.AllowGet);
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
    }
}

WaterCompany/Areas/Admin/Controllers/DriverController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaterCompany.Core;
using WaterCompanyViewModel.Admin;

namespace WaterCompany.Areas.Admin.Controllers
{
    public class DriverController : Controller
    {
        // GET: Admin/Driver
        #region Actions
        public ActionResult Index()
        {
            //var model = "DriversSelectAll".ExecuParamsSqlOrStored(false).AsList<DriverVM>();
            return View();
        }
        public ActionResult Search()
        {
            var model = "DriversSelect".ExecuParamsSqlOrStored(false).AsList<DriverVM>();

            return PartialView(model);
        }
        [HttpGet]
        public ActionResult Create(int CarId=0,int MangerId=0)
        {
            var lst2 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst2.AddRange("EmpDrop".ExecuParamsSqlOrStored(false).AsList<EmployeeDrop>().Select(s => new SelectListItem
            {
                Text = s.NameAr,
                Value = s.Id.ToString(),
                Selected = s.Id == MangerId ? true : false
            }).ToList());
            ViewBag.ManagerId = lst2;

            var lst3 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst3.AddRange("CarDrop".ExecuParamsSqlOrStored(false).AsList<CarDrop>().Select(s => new SelectListItem
            {
                Text = s.TypeCars+s.NumberCars,
                Value = s.Id.ToString(),
                Selected = s.Id == CarId ? true : false
            }).ToList());
            ViewBag.carId = lst3;
            var lst4 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst4.AddRange("Sp_RegionDrop".ExecuParamsSqlOrStored(false).AsList<RegionVM>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());
            ViewBag.RegionId = lst4;

            DriverFM obj = new DriverFM();
            return PartialView("~/Areas/Admin/Views/Driver/Create.cshtml", obj);
        }
        [HttpGet]
        public ActionResult Edit(int Id ,int MangerId = 0,int CarId=0)
        {
            var lst2 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst2.AddRange("EmpDrop".ExecuParamsSqlOrStored(false).AsList<EmployeeDrop>().Select(s => new SelectListItem
            {
                Text = s.NameAr,
                Value = s.Id.ToString(),
                Selected = s.Id == MangerId ? true : false
            }).ToList());
            ViewBag.ManagerId = lst2;

            var lst3 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst3.AddRange("CarDrop".ExecuParamsSqlOrStored(false).AsList<CarDrop>().Select(s => new SelectListItem
            {
                Text = s.TypeCars + s.NumberCars,
                Value = s.Id.ToString(),
                Selected = s.Id == CarId ? true : false
            }).ToList());
            ViewBag.carId = lst3;
            var lst4 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst4.AddRange("Sp_RegionDrop".ExecuParamsSqlOrStored(false).AsList<RegionVM>().Select(s => new SelectListItem
            {
                Text = s.Name,
                Value = s.Id.ToString(),
                Selected = s.Id == 0 ? true : false
            }).ToList());
            ViewBag.RegionId = lst4;
            var model = "DriversSelectById".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsList<DriverFM>();
            return PartialView("~/Areas/Admin/Views/Driver/Create.cshtml", model.FirstOrDefault());
        }
        [HttpPost]

        public ActionResult Create(DriverFM model)
        {

            
            var data = "DriversInsert".ExecuParamsSqlOrStored(false, "NameAr".KVP(model.NameAr),
                "NameEn".KVP(model.NameEn), "Telephone".KVP(model.Telephone), "Address".KVP(model.Address),
                "PercentAmount".KVP(model.PercentAmount), "Area".KVP(model.Area), "ManagerId".KVP(model.ManagerId),
                "CarId".KVP(model.CarId),
                "Note".KVP(model.Note),
                                "RegionId".KVP(model.RegionId),

                "Id".KVP(model.Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "Add Success", JsonRequestBehavior.AllowGet);


            }


            return Json("error," + " Error", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int Id)
        {
            //var data = "DriversDelete".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            DriverFM obj = new DriverFM();
            obj.Id = Id;
            return PartialView("~/Areas/Admin/Views/Driver/Delete.cshtml", obj);



        }
        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "DriversDelete".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();

            if (data == 1)
                return Json("success," + "Delete Success", JsonRequestBehavior.AllowGet);
            else
                return Json("error," + "Error", JsonRequestBehavior.AllowGet);
        }
        #endregion
    }
}

WaterCompany/Areas/Admin/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaterCompany.Core;
using WaterCompanyViewModel.Admin;

namespace WaterCompany.Areas.Admin.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Admin/Employee
        public ActionResult Index()
        {
            //var model = "ProductsSelectAll".ExecuParamsSqlOrStored(false).AsList<EmployeeVM>();
            return View();
        }
        public ActionResult Search()
        {
            var model = "EmployeesSelect".ExecuParamsSqlOrStored(false).AsList<EmployeeVM>();

            return PartialView(model);
        }
        [HttpGet]
        public ActionResult Create(int EmployeeId=0)
        {

            EmployeeVM obj = new EmployeeVM();
            var lst2 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst2.AddRange("EmpPositionDrop".ExecuParamsSqlOrStored(false).AsList<EmployeeDrop>().Select(s => new SelectListItem
            {
                Text = s.NameAr,
                Value = s.Id.ToString(),
                Selected = s.Id == EmployeeId ? true : false
            }).ToList());
            ViewBag.PositionId = lst2;
            return PartialView("~/Areas/Admin/Views/Employee/Create.cshtml", obj);
        }
        [HttpGet]
        public ActionResult Edit(int Id,int EmployeeId=0)
        {
            EmployeeVM obj = new EmployeeVM();
            var lst2 = new List<SelectListItem> { new SelectListItem { Text = "الكل", Value = "0" } };
            lst2.AddRange("EmpPositionDrop".ExecuParamsSqlOrStored(false).AsList<EmployeeDrop>().Select(s => new SelectListItem
            {
                Text = s.NameAr,
                Value = s.Id.ToString(),
                Selected = s.Id == EmployeeId ? true : false
            }).ToList());
            ViewBag.PositionId = lst2;
            var model = "EmployeesSelectById".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsList<EmployeeVM>();
            return PartialView("~/Areas/Admin/Views/Employee/Create.cshtml", model.FirstOrDefault());
        }
        [HttpPost]

        public ActionResult Create(EmployeeVM model)
        {
            

            var data = "EmployeesInsert".ExecuParamsSqlOrStored(false, "NameAr".KVP(model.NameAr),
                "NameEn".KVP(model.NameEn),
                "PositionId".KVP(model.PositionId),
                "Telephone".KVP(model.Telephone), "Address".KVP(model.Address),
                 "PercentAmount".KVP(model.PercentAmount),
                
               
                "Note".KVP(model.Note),
                "Id".KVP(model.Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "Add Success", JsonRequestBehavior.AllowGet);


            }


            return Json("error," + " Error", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int Id)
        {
            //var data = "SP_DeleteCategory".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            EmployeeVM obj = new EmployeeVM();
            obj.Id = Id;
            return PartialView("~/Areas/Admin/Views/Employee/Delete.cshtml", obj);



        }
        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "EmployeesDelete".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();

            if (data == 1)
                return Json("success," + "Delete Success", JsonRequestBehavior.AllowGet);
            else
                return Json("error," + "Error", JsonRequestBehavior.AllowGet);
        }
    }
}

WaterCompany/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WaterCompany.Core;
using WaterCompanyViewModel.Admin;

namespace WaterCompany.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        // GET: Admin/Product
        public ActionResult Index()
        {
            //var model = "ProductsSelectAll".ExecuParamsSqlOrStored(false).AsList<ProductVM>();
            return View();
        }
        public ActionResult Search()
        {
            var model = "ProductsSelectAll".ExecuParamsSqlOrStored(false).AsList<ProductVM>();

            return PartialView(model);
        }
        [HttpGet]
        public ActionResult Create()
        {

            ProductVM obj = new ProductVM();
            return PartialView("~/Areas/Admin/Views/Product/Create.cshtml", obj);
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var model = "ProductsSelectById".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsList<ProductVM>();
            return PartialView("~/Areas/Admin/Views/Product/Create.cshtml", model.FirstOrDefault());
        }
        [HttpPost]

        public ActionResult Create(ProductVM model)
        {




            var data = "ProductsInsert".ExecuParamsSqlOrStored(false, "NameAr".KVP(model.NameAr),
                "NameEn".KVP(model.NameEn), "DescAr".KVP(model.DescAr), "DescEn".KVP(model.DescEn),
                "Price".KVP(model.Price), "Note".KVP(model.Note), 
                "Id".KVP(model.Id)).AsNonQuery();
            if (data != 0)
            {
                return Json("success," + "Add Success", JsonRequestBehavior.AllowGet);


            }


            return Json("error," + " Error", JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int Id)
        {
            //var data = "SP_DeleteCategory".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();
            ProductVM obj = new  ProductVM();
            obj.Id = Id;
            return PartialView("~/Areas/Admin/Views/Product/Delete.cshtml", obj);



        }
        [HttpPost]

        public JsonResult DeleteRow(int Id)
        {
            var data = "ProductsDelete".ExecuParamsSqlOrStored(false, "Id".KVP(Id)).AsNonQuery();

            if (data == 1)
                return Json("success," + "Delete Success", JsonRequestBehavior.AllowGet);
            else
                return Json("error," + "Error", JsonRequestBehavior.AllowGet);
        }
    }
}

WaterCompany/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WaterCompany/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WaterCompany/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<section id="content" class="">

    <br /><br /><br /><br />

    <div class="admin-panels fade-onload">

        <div class="topbar-menu row">

            <div class="col-md-3 col-sm-6 col-xs-12">
                <a class="dropmenu-tile " href="@Url.Action("index", "Employee" , new { area="Admin" })">
                    <div class="imagenew">

                        <img src="~/assets/images/iconsnew/usericon.png" width="70" height="70" />

                        <span class="tile-title">
                            الموظفين
                            @*<p class="newsp">Manage accounts and roles</p>*@

                        </span>
                    </div>
                </a>
            </div>

            <div class="col-md-3 col-sm-6 col-xs-12">
                <a class="dropmenu-tile " href="@Url.Action("index", "Delegate" , new { area="Admin" })">
                    <div class="imagenew">

                        <img src="~/assets/images/iconsnew/usericon.png" width="70" height="70" />

                        <span class="tile-title">
                            المندوبين
                            @*<p class="newsp">Manage accounts and roles</p>*@

                        </span>
                    </div>
                </a>
            </div>

            <div class="col-md-3 col-sm-6 col-xs-12">
                <a class="dropmenu-tile " href="@Url.Action("index", "ManagementCars" , new { area="Admin" })">
                    <div class="imagenew">

                        <img src="~/assets/images/iconsnew/Pos.png" width="70" height="70" />

                        <span class="tile-title">
                            السيارات
                        </span>
                    </div>
                </a>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <a class="dropmenu-tile " href="@Url.Action("index", "Driver" , new { area="Admin" })">
                    <div class="imagenew">

                        <img src="~/assets/images/iconsnew/Pos.png" width="70" height="70" />

                        <span class="tile-title">
                            السائقين
                        </span>
                    </div>
                </a>
            </div>

            <div class="col-md-3 col-sm-6 col-xs-12">
                <a class="dropmenu-tile " href="@Url.Action("index", "Product" , new { area="Admin" })">
                    <div class="imagenew">

                        <img src="~/assets/images/iconsnew/Sim.png" width="70" height="70" />

                        <span class="tile-title">
                            المنتجات
                        </span>
                    </div>
                </a>
            </div>

            <div class="col-md-3 col-sm-6 col-xs-12">
                <a class="dropmenu-tile " href="@Url.Action("index", "ManageInvoice", new { area = "Invoice" })">
                    <div class="imagenew">

                        <img src="~/assets/images/iconsnew/paper.png" width="70" height="70" />

                        <span class="tile-title">
                            الفواتير
                        </span>
                    </div>
                </a>
            </div>
            <div class="col-md-3 col-sm-6 col-xs-12">
                <a class="dropmenu-tile " href="@Url.Action("index", "ManageAgreement" , new { area="Agreement" })">
                    <div class="imagenew">

                        <img src="~/assets/images/iconsnew/paper.png" width="70" height="70" />

                        <span class="tile-title">
                            التعاقدات
                        </span>
                    </div>
                </a>
            </div>

            @*<div class="col-md-3 col-sm-6 col-xs-12">
                    <a class="dropmenu-tile " href="#">
                        <div class="imagenew">

                            <img src="~/assets/images/iconsnew/Tickets.png" width="70" height="70" />

                            <span class="tile-title">
                                Tickets
                                <p class="newsp">Add & assign Tickets</p>

                            </span>
                        </div>
                    </a>
                </div>

                <div class="col-md-3 col-sm-6 col-xs-12">
                    <a class="dropmenu-tile " href="#">
                        <div class="imagenew">

                            <img src="~/assets/images/iconsnew/Withdrae.png" width="70" height="70" />

                            <span class="tile-title">
                                WithDraw

                                <p class="newsp">Add & Withdraw logs</p>
                            </span>
                        </div>
                    </a>
                </div>

                <div class="col-md-3 col-sm-6 col-xs-12">
                    <a class="dropmenu-tile " href="#">
                        <div class="imagenew">

                            <img src="~/assets/images/iconsnew/reports.png" width="70" height="70" />

                            <span class="tile-title">
                                Reports

                                <p class="newsp">Discover System Reports </p>
                            </span>
                        </div>
                    </a>
                </div>*@
        </div>




    </div>

</section>